server:
  port: 8080
  servlet:
    context-path: /robotplatform

spring:
  application:
    name: robotplatform

# 机器人AI配置
robotplatform:
  # FunASR配置
  funasr:
    serverUrl: ws://192.168.0.103:10096
    heartbeatInterval: 30

  
  # CosyVoice配置
  cosyvoice:
    server:
      host: 100.68.113.25
      port: 50000
    voice:
      id: 中文女
  
  # Ollama配置
  ollama:
    server:
      url: http://192.168.0.103:11434
    model: qwen2.5:14b
    timeout:
      seconds: 60
  dify:
    api:
      base-url: https://dify.aipromaker.cn/v1
      default-key: app-xrRJLyVs3iqDEldmFr9FHglT